myapp/urls.py
from django.urls import path
from myapp import views
from . import views
app_name = 'myapp'
urlpatterns = [
 path(r'', views.index, name='index'),
 path(r'about', views.about, name='about'),
 path(r'<int:topic_id>', views.detail, name='detail'),
 path(r'findcourses', views.findcourses, name='findcourses'),
 path(r'placeorder', views.placeorder, name='placeorder'),
 path(r'review', views.review, name='review'),
 path(r'login', views.user_login, name='login'),
 path(r'logout', views.user_logout, name='logout'),
 path(r'myaccount', views.myaccount, name='myaccount'),
 path(r'register', views.register, name='register'),
 path(r'passowrd/password_reset', views.password_reset_request, name='password_reset')

 ]

mysiteS21/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

]

myapp/models.py
from django.db import models
from django.db.models import Sum

import datetime
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


class Topic(models.Model):
    name = models.CharField(max_length=200)
    length = models.IntegerField(default=12, blank=False)

    def __str__(self):
        return '%s' % (self.name)


class Course(models.Model):
    title = models.CharField(max_length=200)
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    # topic= models.ManyToManyField(Topic, blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(blank= True)
    num_reviews = models.PositiveIntegerField(default=0)

    def topic_length(self):
        return str(self.topic.length)
    def topic_name(self):
        return str(self.topic.name)

    def __str__(self):
        return '%s' % (self.title)

class Student(User):
    LVL_CHOICES = [
    ('HS', 'High School'),
    ('UG', 'Undergraduate'),
    ('PG', 'Postgraduate'),
    ('ND', 'No Degree'),
    ]
    level = models.CharField(choices=LVL_CHOICES, max_length=2, default='HS')
    address = models.CharField(max_length=300)
    province=models.CharField(max_length=2, default='ON')
    registered_courses = models.ManyToManyField(Course, blank=True)
    interested_in = models.ManyToManyField(Topic)
    address = models.CharField(max_length=100, blank=False)

    def upper_case_name(self):
        return ('%s %s' % (self.first_name,self.last_name)).upper()
    upper_case_name.short_description="Student Full Name"

    def __str__(self):
        return '%s' % self.username

class Order(models.Model):
    courses = models.ManyToManyField(Course)
    Student = models.ForeignKey(Student, name="Student", on_delete=models.CASCADE,default="john")
    order_values_map = [(0, 'Cancelled'), (1, 'Confirmed'), (2, 'On Hold')]
    order_status=models.IntegerField(default=1, choices=order_values_map)
    order_date = models.DateField(default=timezone.now)

    def total_cost(self):
        return '%s ordered courses worth %s' % (self.Student,self.courses.aggregate(
            total_price=Sum('price')
        )['total_price'])
    def total_items(self):
        return self.courses.count()

    def __str__(self):
        return self.total_cost()

class Review(models.Model):
    reviewer = models.EmailField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comments = models.TextField()
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return "Reviewed by :%s \nFor Course:%s\nRating:%s\nComments:%s" % (self.reviewer,self.course,self.rating,self.comments)

myapp/forms.py
from django import forms
from django.forms import PasswordInput

from myapp.models import Order, Review, Student


class SearchForm(forms.Form):
    LENGTH_CHOICES = [
        (8, '8 Weeks'),
        (10, '10 Weeks'),
        (12, '12 Weeks'),
        (14, '14 Weeks'),
    ]
    name = forms.CharField(max_length=100, required=False, label="Student Name:")
    length = forms.TypedChoiceField(widget=forms.RadioSelect,choices=LENGTH_CHOICES,label="Preferred course duration:", coerce=int,required=False)
    max_price = forms.IntegerField(min_value=0,label="Maximum Price")

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['courses', 'Student', 'order_status']
        widgets = {'courses': forms.CheckboxSelectMultiple(),
                   'order_type': forms.RadioSelect}
        labels = {'student': u'Student Name' }

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['reviewer', 'course', 'rating', 'comments']
        widgets = {'course':forms.RadioSelect}
        labels = {'reviewer': u'Please enter a valid email',
                  'rating':u'Rating: An integer between 1 (worst) and 5 (best)'}
    def __init__(self,*args,**kwargs):
        super(ReviewForm, self).__init__(*args,**kwargs)
        self.fields['course'].empty_label=None

class RegisterForm(forms.ModelForm):
    class Meta:
        model = Student
        fields=['username', 'password','first_name','last_name', 'address', 'interested_in']
        widgets = {'interested_in': forms.CheckboxSelectMultiple(),'password':forms.PasswordInput()}
        labels={
            'username':u'Username:',
            'passowrd':u'Passowrd:',
            'first_name':u'First Name:',
            'last_name': u'Last Name:',
            'address' : u'City:',
            'interested_in': u'Courses you are interested in:'
        }
        
    def __init__(self,*args,**kwargs):
        super(RegisterForm, self).__init__(*args,**kwargs)
        self.fields['interested_in'].empty_label=None

myapp/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse, HttpResponseRedirect, response
from django.urls import reverse
from .forms import SearchForm, OrderForm, ReviewForm, RegisterForm
from .models import Topic, Course, Student, Order, Review
from django.shortcuts import get_object_or_404
# Create your views here.
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "main/password/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'mysiteS21',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="main/password/password_reset.html",
                  context={"password_reset_form": password_reset_form})


def user_login(request):
    print(request.get_full_path())

    if(request.GET.get('next')):
        request.session['profile']=request.GET.get('next')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                if('profile' in request.session.keys()):
                    if('myapp/myaccount' in request.session['profile']):
                        return HttpResponseRedirect(reverse('myapp:myaccount'))
                else:
                    return HttpResponseRedirect(reverse('myapp:index'))

            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('myapp:index')))


def index(request):
    top_list = Topic.objects.all().order_by('id')[:10]
    login_time = request.session.get('last_login', 'over 1 hour ago')
    return render(request, 'myapp/index.html', {'top_list': top_list, 'name': request.user})


# ------Lab 5 content-------
# top_list = Topic.objects.all().order_by('id')[:10]
# response = HttpResponse()
# heading1 = '<p>' + 'List of topics: ' + '</p>'
# response.write(heading1)
# for topic in top_list:
#     para = '<p>'+ str(topic.id) + ': ' + str(topic) + ':</p>'
#     response.write(para)
#
#     response.write('<ul>')
#     for courses in Course.objects.filter(topic_id=topic.id).order_by('-title')[:5]:
#         list = '<li>'+str(courses)+': $'+str(courses.price)+'</li>'
#         response.write(list)
#     response.write('</ul>')

# return response

def about(request):
    response = HttpResponse()
    heading = '<p>' + 'This is new E-Learning platform! Enjoy learning in a new way' + '</p>'
    response.write(heading)
    visits = int(request.COOKIES.get('about_visits', '0'))
    visits += 1
    max_age = 300
    last_user = request.COOKIES.get('last_user', 'New User')
    response = render(request, 'myapp/about.html',
                      {'user': request.user, 'about_visits': visits, 'last_user': last_user})
    response.set_cookie('about_visits', visits, max_age=max_age)
    response.set_cookie('last_user', request.user.username)
    return response
    # return HttpResponsePermanentRedirect(reverse('about'))


def detail(request, topic_id):
    response = HttpResponse()
    topic = get_object_or_404(Topic, id=topic_id)
    course_list = Course.objects.filter(topic=topic)
    response = HttpResponse()
    for course in course_list:
        para = '<p>' + str(course.title.upper()) + "is of " + str(course.topic.length) + "$weeks" + "</p>"
    response.write(para)
    return render(request, 'myapp/detail.html', {'course_list': course_list})
    # ---lab5 --content:
    # response.write('<h3>'+ topic.name.upper() +"</h3>")
    # response.write('Length:'+ str(topic.length))
    # for courses in Course.objects.filter(topic_id=topic_id).order_by('title')[:5]:
    #     list = '<p>'+ str(courses) +': $'+ str(courses.price)+ '</p>'
    #     response.write(list)
    #
    # return response


def findcourses(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            length = form.cleaned_data['length']
            maxPrice = form.cleaned_data['max_price']
            topics = Topic.objects.filter(length=length)
            courselist = {}
            if length == 0:  # user did not select a course length
                courselist = Course.objects.filter(price__lte=maxPrice)
                return render(request, 'myapp/results.html',
                              {'courselist': courselist, 'name': name, 'price': maxPrice})
            else:
                for top in topics:
                    courselist[top] = list(top.courses.all() and top.courses.filter(price__lte=maxPrice))
                return render(request, 'myapp/results.html',
                              {'courselist': courselist, 'name': name, 'length': length, 'price': maxPrice})
        else:
            return HttpResponse('Invalid data')
    else:
        form = SearchForm()
        return render(request, 'myapp/findcourses.html', {'form': form, 'name': request.user})


def placeorder(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            courses = form.cleaned_data['courses']
            order = form.save(commit=True)
            student = order.Student
            status = order.order_status
            order.save()
            if status == 1:
                for c in order.courses.all():
                    student.registered_courses.add(c)
                return render(request, 'myapp/order_response.html',
                              {'courses': courses, 'order': order, 'name': request.user})
        else:
            return render(request, 'myapp/place_order.html', {'form': form, 'name': request.user})
    else:
        form = OrderForm()
        return render(request, 'myapp/place_order.html', {'form': form, 'name': request.user})


def review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            rating = form.cleaned_data['rating']
            course_name = form.cleaned_data['course']
            reviewer = form.cleaned_data['reviewer']
            comments = form.cleaned_data['comments']
            if rating in range(0, 6):
                review_obj = Review.objects.create(reviewer=reviewer, course=course_name, rating=rating,
                                                   comments=comments)
                review_obj.save()
                update_review = Course.objects.get(title=course_name)
                update_review.num_reviews += 1
                update_review.save()
                return redirect('/myapp/')
            else:
                form = ReviewForm()
                messages.info(request, 'PLease rate on scale of 5 :)')
                return render(request, 'myapp/review.html', {'form': form, 'name': request.user})
        return render(request, 'myapp/review.html', {'form': form, 'name': request.user})
    else:
        form = ReviewForm()
        return render(request, 'myapp/review.html', {'form': form, 'name': request.user})


@login_required
def myaccount(request):
    print("entered my accout")
    if request.user.is_authenticated:
        user_name = request.user.username
        fname = User.first_name
        lname = User.last_name
        #course_list = Student.objects.filter(username=user_name).first().registered_courses.all()
        #topics = Student.objects.filter(username=user_name).first().interested_in.all()
        try:
            course_list = Student.objects.filter(username=user_name).first().registered_courses.all()
            topics = Student.objects.filter(username=user_name).first().interested_in.all()
        except AttributeError as e:
            return render(request, 'myapp/myaccount.html')
        return render(request, 'myapp/myaccount.html',

templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block title %}
eLearning - APP About page
{% endblock %}
<h3>{% block myhdg %}Hello {{request.user.first_name}} {{ request.user.last_name }} {% endblock %}</h3>
{% block body_block %}
    <p>This is new E-Learning platform! Enjoy learning in a new way</p>
    <p>About page has been visited {{ about_visits }} times.</p>
{% endblock %}

templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <p>This is new E-Learning platform! Enjoy learning in a new way</p>
    <p><a href="{% url 'myapp:index' %}">Landing page</a></p>
    <p><a href="/myapp/">Home</a></p>

</body>
</html>

templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>E-Learning WebApp - {% block title %} Welcome! {% endblock %}</title>
</head>
<body>
<div>
    <h3>{% block myhdg %}Hello {{request.user.first_name}} {{ request.user.last_name }} {% endblock %}</h3>
    {% block body_block %}*** {% endblock %}

</div>
<hr/>


</body>
<footer class="page-footer font-small blue">
    <div class="footer-copyright text-center py-3">
    <ul>
        <li class="hbar1"><a href="{% url 'myapp:about' %}">About Us</a></li>
        <li class="hbar1"><a href="{% url 'myapp:index' %}">
            Main</a></li>
        <li class="hbar1"><a href="{% url 'myapp:findcourses' %}">Find Courses</a></li>
        <li class="hbar1"><a href="{% url 'myapp:placeorder' %}">Place Order</a></li>


        {% if request.user.is_authenticated %}
            <li class="hbar1"><a href="{% url 'myapp:myaccount' %}">Profile</a></li>
            <li class="hbar1"><a href="{% url 'myapp:logout' %}">Logout</a></li>

        {% else %}
            <li class="hbar1"><a href="{% url 'myapp:login' %}">Login</a></li>
            <li class="hbar1"><a href="{% url 'myapp:register' %}">Register</a></li>
        {% endif %}





    </ul>
        </div>
</footer>
</html>

templates/myapp/detail.html
{% extends 'myapp/base.html' %}
<h3>{% block myhdg %}Hello {{request.user.first_name}} {{ request.user.last_name }} {% endblock %}</h3>
{% block body_block %}

    {% if course_list %}

    <h2>Courses:</h2>
    {% for course in course_list %}
        <p>{{ course.title }} is of {{ course.topic.length }} weeks</p>
    {% endfor %}
    {% else %}
    <strong>No courses</strong>
    {% endif %}
{% endblock %}

templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
{% if course_list %}
    <h2>Courses:</h2>
    {% for course in course_list %}
        <p>{{ course.title }} is of {{ course.topic.length }} weeks</p>
    {% endfor %}
    {% else %}
    <strong>No courses</strong>
{% endif %}

</body>
</html>

templates/myapp/index.html
{% extends 'myapp/base.html' %}
<h3>{% block myhdg %}Hello {{request.user.first_name}} {{ request.user.last_name }} {% endblock %}</h3>

{% block body_block%}
    <div class="container">
    <div class="row justify-content-md-center">
       <div class="col-md-auto">

       </div>
        <div class="col-md-auto">
            {% if top_list %}
            <p class="myheading">List of Topics</p>
            <ol>
                {% for top in top_list %}
                    <li><a href="{{ forloop.counter }} "> {{ top.name }}</a> </li>
                {% endfor %}
            </ol>
            {% else %}
                <strong>There are no available topics!</strong>
            {% endif %}

            <p>Last login {{ last_login }}</p>
       </div>
        <div class="col-md-auto">

       </div>
    </div>

    </div>
{#<p><a href="{% url 'myapp:about' %}">About Page</a></p>#}

{% endblock %}

templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>
<body>
{% if top_list %}
    <h2>List of Topics</h2>
    <ol>
        {% for top in top_list %}
            <li> {{ top.name }} </li>
        {% endfor %}
    </ol>
{% else %}
    <strong>There are no available topics!</strong>
{% endif %}
<p><a href="{% url 'myapp:about' %}">About Page</a></p>

</body>
</html>

templates/myapp/login.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <form id="login" method="post" action="{% url 'myapp:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" placeholder="username" size="50"/>
    <br />
        Password: <input type="password" name="password" placeholder="password" size="50"/>
    <br />
        <input type="hidden" name="next" value="{{ next }}">
    <input type="submit" value="Login"/>
    </form>
     <a href="/password_reset">Forgot password?</a>
{% endblock %}

templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}
<h3>{% block myhdg %}Hello {{request.user.first_name}} {{ request.user.last_name }} {% endblock %}</h3>
{% block body_block %}
    {% if topics %}
        <h2>Interested Topics:</h2>
        {% for topic in topics %}
            <li><b>{{ topic.name }}</b></li>
        {% endfor %}
    {% else %}
        <strong>Nothing here!</strong>
    {% endif %}

    {% if course_list %}
        <p>Registered Courses:</p>
        {% for course in course_list %}
            <p><b>{{ course.title }}</b> with duration of <em>{{ course.topic.length }} weeks</em>.</p>
        {% endfor %}
    {% else %}
        <strong>No registered courses!</strong>
    {% endif %}
{% endblock %}

templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
<h3>{% block myhdg %}Hello {{request.user.first_name}} {{ request.user.last_name }} {% endblock %}</h3>
{% block body_block %}
    {% if courses %}
        <h2>List of ordered Courses:</h2>
        {% for course in courses %}
            <p>{{ forloop.counter }}.) {{ course.title }} has been purchased for ${{ course.price }}.</p>
        {% endfor %}
    {% else %}
        <strong>Nothing!</strong>
    {% endif %}
{% endblock %}

templates/myapp/place_order.html
{% extends 'myapp/base.html' %}
<h3>{% block myhdg %}Hello {{request.user.first_name}} {{ request.user.last_name }} {% endblock %}</h3>
{% load static %}
{% block body_block %}
     <div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-auto">

       </div>
        <div class="col-md-auto">
        <form action="{% url 'myapp:placeorder' %}" method="post">
         {% csrf_token %}
         {{ form.as_p }}
         <input id="OrderBtn"type="submit" name="submit1" value="Place Order" />
         </form>
       </div>
        <div class="col-md-auto">

       </div>

    </div>
     </div>
{% endblock %}

templates/myapp/register.html
{% extends 'myapp/base.html' %}
<h3>{% block myhdg %}Hello {{request.user.first_name}} {{ request.user.last_name }} {% endblock %}</h3>
{% block body_block %}

    <form action="{% url 'myapp:register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="register" value="Register"/>
    </form>
{% endblock %}

templates/myapp/results.html
{% extends 'myapp/base.html' %}
{% load static %}
<h3>{% block myhdg %}Hello {{request.user.first_name}} {{ request.user.last_name }} {% endblock %}</h3>
 {% block body_block %}
{#     c={{ courselist }}#}

    <br>
{#     <label>Category:</label>{{ category }}#}
{#    <br>#}
<div style="font: normal normal normal 15px Poppins;">
     <h2 >
         Courses with {{ length }} weeks under {{ price }}$ are listed below:
     </h2>

     <ul>

        {% for k,v in courselist.items %}
            <b><li>{{ k }}</li></b>
                <ol>
                {% for j in v %}
                    <li>{{ j }}</li>
                    {% endfor %}
                </ol>
            {% endfor %}
    </ul>
</div>
 {% endblock %}

templates/myapp/review.html
{% extends 'myapp/base.html' %}
<h3>{% block myhdg %}Hello {{request.user.first_name}} {{ request.user.last_name }} {% endblock %}</h3>
{% block body_block %}
    {% if messages %}
        <div class="alert">
            {% for message in messages %}
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;{{ message }}</span>
            {% endfor %}
        </div>
    {% endif %}
 <form action="{% url 'myapp:review' %}" method="post">
 {% csrf_token %}
 {{ form.as_p }}
 <input type="submit" name="submit1" value="Leave Review" />
 </form>
{% endblock %}